config/routes.rb
Rails.application.routes.draw do

 
	get root 'gossips#index'
	get 'about/welcome/:first_name', to: 'about#welcome'
	get 'about/team'
	get 'about/contact'

	resources :gossips do
	  resources :comments
	  resources :likes
	end
	resources :users
	resources :cities
	resources :session, only: [:new, :create, :destroy] 

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
	end

  def index
  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end


  def destroy
    log_out if logged_in?
    redirect_to new_session_path
  end

end

app/helpers/session_helper.rb
module SessionHelper

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

		#As with log_in, in the Sessions helper,we define a remember method that 
		#calls user.remember, thereby generating a remember token 
		#and saving its digest to the database. 
		#It then uses cookies to create permanent cookies for the user id 
		#and remember token as described above. Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

   # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

    # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end


	def logged_in?
		if session[:user_id] != nil
			return true
		else
			return false
		end
	end

# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/views/session/new.html.erb
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: session_index_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", new_user_path %></p>
  </div>
</div>