config/routes.rb
Rails.application.routes.draw do

 
	get root 'gossips#index'
	get 'about/welcome/:first_name', to: 'about#welcome'
	get 'about/team'
	get 'about/contact'

	resources :gossips do
	  resources :comments
	  resources :likes
	end
	resources :users
	resources :cities
	resources :session, only: [:new, :create, :destroy] 

end

app/models/gossip.rb
class Gossip < ApplicationRecord

	validates :title, length: { minimum: 3, maximum: 14},
	presence: true
	validates :content, 
	presence: true

	belongs_to :user
	has_many :comments
	has_many :join_tag_to_gossips
	has_many :tags, through: :join_tag_to_gossips
	has_many :likes, dependent: :destroy

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :show]

  def index
    @gossip = Gossip.all
  end

  def show
    @gossip_precis = Gossip.find(params[:id])
    @gossip_user_id = @gossip_precis.user_id
    @gossip_user_city_id = User.find(@gossip_user_id).city_id
    @gossip_user_city = City.find(@gossip_user_city_id).name
    # @comment = Comment.new
  end  

  def new
    @gossip_new = Gossip.new
  end

  def create
    # anonymous = User.find_by(last_name: "Nymous")
    @gossip_new = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    @gossip_new.save

    if @gossip_new.save
    	redirect_to action:'index'
    	flash[:success] = "Your gossip has been registered with success, my coño friend!"
    else
    	render 'new'
    end

    puts @gossip_new.user 
  end

  def edit
    @gossip_precis = Gossip.find(params[:id])
    redirect_to root_path, notice: "You can't edit this gossip ma biche"  unless current_user == @gossip_precis.user
   
   
  
  end

  def update
    @gossip_precis = Gossip.find(params[:id])
    if current_user == @gossip_precis.user
      if @gossip_precis.update(gossip_params)
        redirect_to action:'index'
        flash[:success] = "Your gossip has been edited with success, my coño friend!"
      else
        flash[:alert] = "Try again, my coño friend!"
        render :edit
      end
    else 
      redirect_to root_path, notice: "You can't edit this gossip ma biche"  
    end
  end

  def destroy
        @gossip_precis = Gossip.find(params[:id])
      if current_user != @gossip_precis.user
        redirect_to gossip_path(@gossip_precis.id), notice: "You can't delete this gossip ma biche"  
      else
        @gossip_precis.destroy
        redirect_to action: 'index'
        flash[:success] = "Your gossip has been deleted with success, my coño friend!"
      end
  end


private

def gossip_params

  params.require(:gossip).permit(:title, :content)

end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/views/gossips/edit.html.erb
<h1> Editer le potin </h1>
 
<%= form_for @gossip_precis do |f| %>
<div class="form-group">
	<label>Titre</label> 
	<%= f.text_field :title, class: 'form-control'%>
</div>
<div class="form-group">
<label>Contenu du potin</label>
<%= f.text_area :content, class: 'form-control'%>
 </div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Modifier le potin </button>
 </div>
 <% end %>

app/views/gossips/index.html.erb
<div class="card">
  <div class="card-header">
   <h2><center> The Super Gossip Project For Real BITCHEEEEEES </center></h2>
 </div>


</br></br>

<h1>SALUT LES LOULOUS !</h1> 
<p>   

  <% if logged_in? %>

	<h2> 
   <%= link_to " ====> rajoute ton gossip ici <====", new_gossip_path %></h2>
 </div>


</p>
<% @gossip.each do |g| %>

  <div class="row">
    <div class="col-1">
     <img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/Anonymous.svg" class="img-circle" height="55" width="55" alt="Avatar">
   </div>
   <div class="col-11">
    <div class="well">
     <p> <%= "#{g.user.first_name} #{g.user.last_name}" %></p>

     <p> comment: <span class="badge badge-primary badge-pill"> <%=g.comments.count %></span> </p>

   </div>
 
  <div class="row-2">
    <div class="well">
      <p><%= link_to "#{g.title}", gossip_path(g.id) %></p>

    <% pre_like = g.likes.find { |like| like.user_id == current_user.id} %>
   <% if pre_like %>
     <%= button_to 'Unlike', gossip_like_path(g, pre_like), method: :delete %>
   <% else %>
     <%= button_to 'Like', gossip_likes_path(g), method: :post %> 
   <% end %>

    <p><span class="badge badge-primary badge-pill"> <%=g.likes.count %> <%= (g.likes.count) == 1 ? 'Like' : 'Likes'%></p></span> </p>
   <br><br>

 
    </div>
  </div>
  </div>
   </div>
<% end %>

<% else %>
<h2> LOG TOI OU SIGN UP MOTHERFUCKER ! </h2>

<% end %>

app/views/gossips/new.html.erb
    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title' %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Create Gossip" %>

    <% end %>
  </br>
  </br>
  </br>

  <% if @gossip_new.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip_new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
<% end %>

app/views/gossips/show.html.erb
 <h3><%= "Gossip  de   #{@gossip_precis.user.first_name} #{@gossip_precis.user.last_name}" %></h3>
   <p> 

  
      <h6> <%= "#{@gossip_precis.title}" %></h6>
      <%= "#{@gossip_precis.content}" %><br>

    <% pre_like = @gossip_precis.likes.find { |like| like.user_id == current_user.id} %>
   <% if pre_like %>
     <%= button_to 'Unlike', gossip_like_path(@gossip_precis, pre_like), method: :delete %>
   <% else %>
     <%= button_to 'Like', gossip_likes_path(@gossip_precis), method: :post %>
   <% end %>
      

 <p><span class="badge badge-primary badge-pill"> <%=@gossip_precis.likes.count %> <%= (@gossip_precis.likes.count) == 1  ? 'Like' : 'Likes'%></p></span> </p>





      <%= "Auteur :" %> <%=link_to " #{@gossip_precis.user.first_name} #{@gossip_precis.user.last_name}", user_path(@gossip_precis.user.id) %><br>
      <%= "Ville :" %><%= link_to " #{@gossip_user_city}", city_path(@gossip_user_city_id) %><br>

       <% if current_user == @gossip_precis.user %> 
      <%= link_to "Editer ce potin", edit_gossip_path(@gossip_precis.id)%><br>
	  <%= link_to 'Annihiler ce potin',
            gossip_path(@gossip_precis),
                        method: :delete,
                        data: { confirm: 'Are you sure of the annihilation ?' } %><br>
      <% end %> 

<%= form_tag gossip_comments_path( controller: :comments, action: :create, gossip_id: @gossip_precis.id ), method: "post" do %>

<div class="form-group">
<label>commentaire</label>
<%= text_area_tag :content %>
 </div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Ajouter le commentaire </button>
 </div>
 <% end %>

 <% @gossip_precis.comments.each do |c|%> 
 <%= "#{c.content}"%> <br>
 <%= "#{c.user.first_name}  #{c.user.last_name}"%><br>
 <%= link_to "Editer ce commentaire", edit_gossip_comment_path(@gossip_precis.id, c.id)%> <br> <br>
 <% end %> 