config/routes.rb
Rails.application.routes.draw do

 
	get root 'gossips#index'
	get 'about/welcome/:first_name', to: 'about#welcome'
	get 'about/team'
	get 'about/contact'

	resources :gossips do
	  resources :comments
	  resources :likes
	end
	resources :users
	resources :cities
	resources :session, only: [:new, :create, :destroy] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	belongs_to :user
validates :content, presence: true, length: { minimum: 1 }
	
end

app/models/gossip.rb
class Gossip < ApplicationRecord

	validates :title, length: { minimum: 3, maximum: 14},
	presence: true
	validates :content, 
	presence: true

	belongs_to :user
	has_many :comments
	has_many :join_tag_to_gossips
	has_many :tags, through: :join_tag_to_gossips
	has_many :likes, dependent: :destroy

end

app/models/join_tag_to_gossip.rb
class JoinTagToGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_tag_to_gossips
	has_many :gossips, through: :join_tag_to_gossips
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :sent_messages, foreign_key: "sender_id", class_name: 'PrivateMessage'
	has_many :received_messages, foreign_key: "recipient_id", class_name: 'PrivateMessage'
	has_many :likes, dependent: :destroy
	validates :password, presence: true, length: { minimum: 6 }
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

	
def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #the User model already has a remember_digest attribute, 
  #but it doesn’t yet have a remember_token attribute. 
  #We need a way to make a token available via user.remember_token (for storage in the cookies)
  # without storing it in the database. We use attr_accessor to create an accessible attribute,

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  #make a user.remember method that associates a remember token with the user 
  #and saves the corresponding remember digest to the database
  # Remembers a user in the database for use in persistent sessions.
  def remember
  	#without self the assignment would create a local variable called remember_token, 
  	#Using self ensures that assignment sets the user’s remember_token attribute.
    self.remember_token = User.new_token
    #the update_attribute method updates the remember digest.
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #we can create a valid token and associated digest by first making a new remember 
  #token using User.new_token, and then updating the remember digest with the result 
  #of applying User.digest. This procedure gives the remember method shown
  #Having created a working user.remember method, we’re now in a position to create a persistent session 
  #by storing a user’s (encrypted) id and remember token as permanent cookies on the browser. 
  #The way to do this is with the cookies method.

   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
  	#The final piece of the puzzle is to verify that a given remember token matches the user’s remember digest
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def team
  end

  def contact
  end

  def welcome
  	puts params[:first_name]
  end
 end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

before_action :find_gossip
before_action :find_like, only: [:destroy]

 
  def create
  	if already_liked?
  		flash[:notice] = "You've already liked this gossip, ma biche"
    else
    	@gossip.likes.create(user_id: current_user.id)
  	end
    redirect_to request.referrer
  end

   def already_liked?
  	Like.where(user_id: current_user.id, gossip_id: 
  		params[:gossip_id]).exists?
  end	

  def find_like
  	@like = @gossip.likes.find(params[:id])
  end

  def destroy
  	@like.delete
  	redirect_to request.referrer
  end

  private

  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

end

app/controllers/users_controller.rb
require 'cities_helper'
class UsersController < ApplicationController

include CitiesHelper

	def show
		@user_precis = User.find(params[:id])
		@user_city_id = @user_precis.city_id
		@user_city = City.find(@user_city_id).name
	end

	def new
		@user = User.new
	end

	def create
		if City.find_by(name: params[:city_name])
			@city_db = City.find_by(name: params[:city_name])
			@user = User.new(email: params[:email], password: params[:password],
				first_name: params[:first_name], last_name: params[:last_name], 
				age: params[:age], city: @city_db)
			@user.save
		else
			@city = City.new(name: params[:city_name], zip_code: params[:zip_code])
			# @city.name = params[:city_name]
			# @city.zip_code =  params[:zip_code]
			@user = User.new(email: params[:email], password: params[:password],
				first_name: params[:first_name], last_name: params[:last_name], 
				age: params[:age], city: @city)
			@user.save
		end


		if @user.save 
			#@city.save
			session[:user_id] = @user.id
			redirect_to root_path
			flash[:success] = "Your account has been created with success, my coño friend!"
		else
			flash[:alert] = "Try again, my coño friend!"

			render 'new'
		end
	end
end

app/helpers/application_helper.rb
	module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info alert-dismissible fade show "
      when 'success' then "alert alert-success alert-dismissible fade show"
      when 'error' then "alert alert-danger alert-dismissible fade show"
      when 'alert' then "alert alert-warning alert-dismissible fade show"
  end
end
end

app/helpers/cities_helper.rb
module CitiesHelper
	def create
		#@city = City.create

		@city = City.new
		@city.save
		#(name: params[:city_name], zip_code: params[:zip_code])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

		#As with log_in, in the Sessions helper,we define a remember method that 
		#calls user.remember, thereby generating a remember token 
		#and saving its digest to the database. 
		#It then uses cookies to create permanent cookies for the user id 
		#and remember token as described above. Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

   # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

    # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end


	def logged_in?
		if session[:user_id] != nil
			return true
		else
			return false
		end
	end

# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-hVpXlpdRmJ+uXGwD5W6HZMnR9ENcKVRn855pPbuI/mwPIEKAuKgTKgGksVGmlAvt" crossorigin="anonymous">

 
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= gossips_path %>">TGP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= gossips_path %>">Home <span class="sr-only"></span></a>
      <a class="nav-item nav-link" href="<%=about_team_path%>">Team</a>
      <a class="nav-item nav-link" href="<%=about_contact_path%>">Contact</a>

      <% if logged_in? != true %>
      <a class="nav-item nav-link" href="<%=new_user_path%>">Sign up</a>
      <a class="nav-item nav-link" href="<%=new_session_path%>">Sign in</a>
      <% else %>

     <span class="nav-item nav-link">  <%= "Bonjour, #{current_user.first_name}" %> </span>
      <span class="nav-item nav-link"><%= link_to "Se déconnecter", session_path(session[:user_id]), method: :delete %></span>
      <% end %>
    

    </div>
  </div>
</nav>


  <div class="container">
    
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> ">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
    </div>
  <% end %>

  <%= yield %>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>